//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ASS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string Available { get; set; }
        public string PatientPatientId { get; set; }
        public string DoctorDoctorId { get; set; }
        public int AdministratorAdministratorId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Administrator Administrator { get; set; }
    }
}
